<a href="https://colab.research.google.com/github/RigoArias/MetodosComputacionales_RigoArias_DarcyGaleano/blob/main/Tarea%204/Tarea_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Ejercicio 4

def multiplicacion_de_matrices(A, B):
    filas_a = len(A)
    columnas_a= len(A[0])
    filas_b = len(B)
    columnas_b = len(B[0])

    r=[]
    for i in range(filas_a):
        nueva_fila = []
        for j in range(columnas_b):
            nueva_fila.append(0)
        r.append(nueva_fila)

    for i in range(filas_a):
        for j in range(columnas_b):
            for k in range(columnas_a):
                r[i][j] += A[i][k] * B[k][j]
    return r

A=[[1,0,0],[5,1,0],[-2,3,1]]
B=[[4,-2,1],[0,3,7],[0,0,2]]
print(multiplicacion_de_matrices(A,B))

[[4, -2, 1], [20, -7, 12], [-8, 13, 21]]


In [ ]:
# Ejercicio 8

import numpy as np

def descomposicion_LU(A):
  n= A.shape[0]
  L= np.zeros((n,n))
  U= np.zeros((n,n))

  for i in range(n):
    for j in range(i,n):
      U[i][j]=A[i][j]
      for k in range(i):
        U[i][j] -= L[i][k]*U[k][j]
    for j in range(i,n):
      if i==j:
        L[i][i]=1
      else:
        L[j][i]=A[j][i]
        for k in range (i):
          L[j][i] -= L[j][k]*U[k][i]
        L[j][i] /= U[i][i]
  return L,U


A= np.array([[4,-2,1],[20,-7,12],[-8,13,17]])
L,U= descomposicion_LU(A)
print(L)
print(U)

[[ 1.  0.  0.]
 [ 5.  1.  0.]
 [-2.  3.  1.]]
[[ 4. -2.  1.]
 [ 0.  3.  7.]
 [ 0.  0. -2.]]


In [ ]:
#Ejercicio 12
#SISTEMA 1
import numpy as np

def f(x):
    x1, x2 = x
    return np.array([
        np.log(x1**2 + x2**2) - np.sin(x1 * x2) - np.log(2) - np.log(np.pi),
        np.exp(x1 - x2) + np.cos(x1 * x2)
    ])

def jacobian(x):
    x1, x2 = x
    return np.array([
        [2 * x1 / (x1**2 + x2**2) - x2 * np.cos(x1 * x2), 2 * x2 / (x1**2 + x2**2) - x1 * np.cos(x1 * x2)],
        [np.exp(x1 - x2), -np.exp(x1 - x2) - x1 * np.sin(x1 * x2)]
    ])

def newton_raphson(x0, tol=1e-10, max_iter=100):
    x = x0
    for _ in range(max_iter):
        J = jacobian(x)
        f_val = f(x)
        delta = np.linalg.solve(J, f_val)
        x = x - delta
        if np.linalg.norm(f_val, ord=2) < tol:
            return x
    return x

x0 = np.array([2, 2])
solution_1 = newton_raphson(x0)

print("Solución del Sistema 1 (Newton-Raphson):")
print(solution_1)

def  descenso_del_gradiente(x0, alpha=0.01, tol=1e-10, max_iter=1000):
    x = x0
    for _ in range(max_iter):
        grad = jacobian(x).T @ f(x)
        x = x - alpha * grad
        if np.linalg.norm(f(x), ord=2) < tol:
            return x
    return x

solution_1_gd = descenso_del_gradiente(x0)

print("\nSolución del Sistema 1 (Descenso del Gradiente):")
print(solution_1_gd)





Solución del Sistema 1 (Newton-Raphson):
[1.77245385 1.77245385]

Solución del Sistema 1 (Descenso del Gradiente):
[1.77245385 1.77245385]
